### ISSUE TITLE
USB issues. 

### ISSUE THREAD

**Issue by Orvis25** [dborth/vbagx#339]
Hey, so I recently installed VBA GX and have discovered a massive issue that is preventing me from playing games.

When I launch a game and start playing, everything is fine. But after like 10 min of playing if i hit the home button to bring up the menu so i can save, my HDD turns off, and the wii no longer recognizes it until I hard reset both the wii, and unplug my hdd.

I think this is an programming issue with something that Snes9x GX. FCEUltraGX, WiiSX and VBA GX use because I have the same problem in all three.

Now i know it is not an HDD issue because I have USB Leader GX installed, and I can play games for hours, close and change games after a few hours without any issues.

Anyone know if this will be patched, or know of a fix?

**Comment by GB-CG** [comment]
Is your HDD powered with a mains plug? Because the Wii USB ports are not powerful enough to support HDD's. The same goes with the Wii U.

If you use a HDD with a mains plug, then it should solve the issue.

**Comment by Orvis25** [comment]
@GB-CG No, my hhd is powered by an external 12v source. 
As I also said. it only happens in Snes9x GX. FCEUltraGX, and VBA GX. They all use the same UI/system so i am positive it is a programming issue/bug because it does not happen when i use USBLoader GX for hours on end.

**Comment by GB-CG** [comment]
@Orvis25 What about using an SD card?

**Comment by Orvis25** [comment]
@GB-CG Have not tried. Do not really want to considering i have everything set up on my hdd already. Would be a pain to re-file everything on my sd card. 

are these projects dead? why is dborth not answering? He wrote the code for them all.

**Comment by Orvis25** [comment]
so i take it this project is dead? No more patches, bug fixes, or updates?

**Comment by GB-CG** [comment]
@Orvis25 I guess not. It's likely to be abandoned.

**Comment by Orvis25** [comment]
Well that sucks. Hope someone will take it over and continue to work on it considering it works on two consoles (wii, and wii U)

**Comment by GB-CG** [comment]
You could try using a USB Y Cable.

**Comment by GB-CG** [comment]
How's the progress? If no luck, the best bet is to ask in the GBAtemp forums.

**Comment by askotx** [comment]
Yeah, this is not a forum... closing
