### ISSUE TITLE
Option to use real GBA as controller?

### ISSUE THREAD

**Issue by MainMemory** [dborth/vbagx#343]
It should be possible to detect a GBA connected to one of the control ports and upload a small GBA homebrew program to it that reports the state of the buttons to the GC/Wii, which can then be read by the emulator. This would allow for a more authentic feeling when playing games.

Here's an example of how to read button state from a GBA: https://github.com/FIX94/gc-gba-link-cable-demo

**Comment by GB-CG** [comment]
If you're interested, the mGBA emulator will incorporate that in a later release.

**Comment by MainMemory** [comment]
If mGBA does add that and VBA-GX doesn't, then I guess I'll have to switch.

**Comment by askotx** [comment]
Then we can close this
