### ISSUE TITLE
Wario Ware Twisted: rotation not working

### ISSUE THREAD

**Issue by xensyria** [dborth/vbagx#347]
Using VBAGX 2.3.6 on Wii, Wario Ware Twisted (U.S. version, .gba format, MD5: 89579f4dfe1ed24a7cd16a6a61a72a17; and Japanese version, .gba format, MD5: d76d992d936c308b7d1bb70ac71a1c37) seems to be emulated 100% correctly, but even with Match Wii controls I can't get it to rotate, making it unplayable.

Rotation/motion controls on Yoshi's Universal Gravitation (Europe) and Kirby Tilt & Tumble (U.S.) work perfectly for me when Match Wii is switched on. Koro Koro Puzzle Happy Panechu also works, though the orientation for Wii Remote-only seems to be the same as when it has Wii Remote + Nunchuck (tilting the D-Pad down always tilts the game forward, rather than to the left which would be good if playing without a Nunchuck).

In WarioWare, with Match Wii switched on, the button mappings for Wii Remote + Nunchuck change from the default (A=A, B=B, Z=R, 1&2 seem to speed up the scrolling text at the bottom). One time when I ran it,  when I pressed a certain button (I think it was C on the Nunchuck, or it may have been B with Wii Remote-only), then the menus turned straight to the left-most option on the screen; when I then let go of the button it moved slightly back to the right, but pressing the button again turned it far to the left again; unlike Universal Gravitation, the screen did not rotate when this happened. Rotating the controllers still didn't affect this at all, and I haven't been able to reproduce it.

I also wondered whether this was somehow linked to the rumble being switched off for my Wii remote, but even after switching rumble back on, rotation isn't working. Switching Match Wii off also doesn't help.

Would it be possible to add a rotation option to the Game Settings/Button Mapping menu, to allow a manual override even if it doesn't recognise the game (e.g. for any homebrewed rotation game, for example)?

**Comment by cheatfreak47** [comment]
Can confirm. 

Hey @FIX94 you're smart with stuffs and it looks like you were messing with vbagx recently, maybe you might have some luck taking a crack at fixing this?

Being able to play WarioWare Twisted again with the motion controls with the new features, like turning frameskip off, sure would be nice.

**Comment by cheatfreak47** [comment]
The last version that worked is release 2.2.8, the next build, 2.3.5 broke it and it'd been broken ever since

**Comment by dborth** [comment]
This is fixed in the codebase now.
