### ISSUE TITLE
Starting VBAGX from Channel Fails

### ISSUE THREAD

**Issue by malfunction54** [dborth/vbagx#349]
After installing vbagx according to the instructions, I ran the installer. The installer ran correctly, but the channel would not start from the Wii Menu.  The distribution creates an "apps/vba-gx" folder.  The installer is looking for "apps/vbagx".  The distribution has a "-" in the name that is not expected by the channel installer.

**Comment by askotx** [comment]
PR are welcome and this repository it's for vbagx not channel installer.
