### ISSUE TITLE
These emulators do not see my FAT32 USB Powered HDD, when i hide it from my wii U 

### ISSUE THREAD

**Issue by morpheousx** [dborth/vbagx#357]
I just discovered that none of the emulators below, detect my USB powered HDD, Formatted to FAT32, when i set the hdd to, "hidden" so the wii u doesn't nag me to format it. I run all 3 emulators among others, via my vwill menu.

When i unhide the hdd, the emulators see the hdd and they work as normal. is there a work around for this or are there versions of these emulators that support hidden hdd drives?

vbagx
snes9xgx
fceugx

**Comment by dborth** [comment]
Use an SD card
