### ISSUE TITLE
Motion controls

### ISSUE THREAD

**Issue by stubl** [dborth/vbagx#364]
When the user sets Match Wii Controls to ON the motion controls invert which is good as users may prefer that, however switching Match Wii Controls back to OFF doesnt invert the motion controls back unless the emulator is turned off and turned on again with Match Wii Controls to OFF still enabled

Ideally this restart would not be needed one way and its odd so I thought to make a post

**Comment by dborth** [comment]
Is this happening for all games or is there a specific one you're having this problem with?

**Comment by stubl** [comment]
With all motion games tho its easier to observe with Kirby Tilt n Tumble, I wanted to invert the motion controls so up/down is left/right by setting Match Wii Controls to ON but I noticed when I set Match Wii Controls back to OFF it didnt change back and you have to restart the emulator with Wii Controls set to OFF still enabled to make it back to the other

My guess is the trigger that inverts when it is set to ON isnt there when it is set to OFF but if restarted on default will go to default

**Comment by dborth** [comment]
[boot.zip](https://github.com/dborth/vbagx/files/2735054/boot.zip)

Okay I think it's fixed, try this build and let me know if everything is working fine.

**Comment by stubl** [comment]
Working great in Kirby and WarioWare

The only quirks I come across is in Yoshi Topsy Turvy Match Controls set to ON rotates the whole screen and in Koro Koro Puzzle switching Match Wii Controls OFF or ON doesnt seem to invert the controls in any way

**Comment by dborth** [comment]
Yeah looks like Topsy Turvy was set to rotate the whole screen on purpose.

And looks like Koro Koro Puzzle wasn't implemented. Closing.
