### ISSUE TITLE
Font file not found

### ISSUE THREAD

**Issue by DDinghoya** [dborth/vbagx#369]
Thank you for your build! :)

When I tried to change language for Korean, no problem apply to Korean on Homebrew channel.

However, Vba's pop-up error massage "Font file not found!" on your attached channel.

Of cause I put ko.tff file into /apps/vbagx

Would you please review for this issue?

Snes9x GX is same issue as VBA Gx and FCE Ultra GX is no problem.

**Comment by dborth** [comment]
I tried all 3 and they all work fine for me. Don't know what to tell you.
