### ISSUE TITLE
Compatibility With Palette Hacks

### ISSUE THREAD

**Issue by redmagejoe** [dborth/vbagx#370]
What steps will reproduce the problem?
1. Load color patched ROMs of Metroid II - Samus Returns (links listed below)
2. Start new game and progress through first few screens
3. Observe color display and compare against other emulators, including VBA for PC.

What is the expected output? What do you see instead?
For Patch 1, backgrounds and some elements should be black. They are instead red. For Patch 2, serious graphical glitches.

What version are you using? On GameCube or Wii?
Wii

Are you using the official build (from the downloads page or auto-update)?
Official Download Google Code Build

Please provide any additional information below.
There seems to be some hiccups with how VBAGX, and thus I would imagine based on online consensus, VBA-M, handles particular palettes. For example, Metroid II has a few very recent and polished color hacks that work famously on VBA, GNUBoy, GNUBoy GX, and a number of other PC GameBoy+ emulators I'd tested on.

https://www.romhacking.net/hacks/175/
http://aderack.com/m2/

The first one seems fairly simple as it seems to turn all black backgrounds or elements bright red. Not sure if that's a simple enough fix. As for EJRT's patch, which would be the ideal patch to use given its adherence to Super Metroid aesthetics, it seems much more complicated and has graphical issues out the arse. I would not be heartbroken if I had to sacrifice this one in favor of the DX version.

**Comment by dborth** [comment]
Sorry, not going to look into this.
