### ISSUE TITLE
VBAGX Forwarder loads to a black screen on Wii U.

### ISSUE THREAD

**Issue by burritosoftware** [dborth/vbagx#372]
On Wii U, loading the VBAGX Forwarder does not load the boot.dol in SD:/apps/vbagx/boot.dol
When this happens, the system gets locked up and requires a hard reboot (unplug and plug of the power cable) to return to normal operation.

**Comment by dborth** [comment]
The forwarder only works on Wii.

**Comment by xXS4ALLx** [comment]
Use TeconMoon's Wii VC Injector script below:
https://gbatemp.net/threads/release-wiivc-injector-script-gc-wii-homebrew-support.483577/
To create your WiiU Forwarder, use the boot.dol and use "Wii Homebrew Injection", I already got a working WiiU Forwarder with GamePad support.
