### ISSUE TITLE
ZL on Wii U Gamepad Not Recognized

### ISSUE THREAD

**Issue by Immortallix** [dborth/vbagx#373]
When playing on a Wii U Gamepad, trying to remap the controls the emulator doesn't seem to recognize the ZL button. If I try to map any GBA button to ZL on the gamepad the mapping just goes blank. Every other button works properly.

**Comment by dborth** [comment]
I don't see any reason why this would be the case, there's nothing special about ZL and everything seems to be correct in the code. Perhaps there's an issue with the wiidrc library but I don't see anything wrong there. Perhaps the newly released version will work for you..

**Comment by Immortallix** [comment]
Just tried it out and still have the same issue.

**Comment by Immortallix** [comment]
Found a fix on a forum. This is what the issue was:
http://www.wiiuiso.com/showthread.php?t=392684&p=1132973#post1132973

**Comment by dborth** [comment]
What's the fix? I don't have an account on that forum.

**Comment by Immortallix** [comment]
This is the post:

"Regarding the ZL button, I've worked it out!

Before I get into the finer details, do the following:

Navigate to the following file on your SD CARD:

SD CARD\vbagx\settings.xml

Open with your preferred txt edit program, and search for the following settings: It's towards the bottom. 

<controller name="drcpadmap" description="Wii U Gamepad">
<button number="0" assignment="4096" />
<button number="1" assignment="16384" />
<button number="2" assignment="4" />
<button number="3" assignment="8" />
<button number="4" assignment="512" />
<button number="5" assignment="256" />
<button number="6" assignment="2048" />
<button number="7" assignment="1024" />
<button number="8" assignment="0" />
<button number="9" assignment="64" />

The string highlighted in RED is the L button mapping, when you try to remap the ZL button in the emulator, it shows up as blank, and in the settings.xml file, the value is "0".
Now change the assignment value to "128", now it should look like the following:

<button number="8" assignment="128" />

Save the settings.xml file, pop the SD CARD back into the WiiU, now boot up VBA GX emulator, boot a game and now go into the Game Settings => Button Mappings => Wii U GamePad, scroll down, now, what do you know, L button is now mapped to ZL :)

Technical Info:
Now onto the technical part, with some investigation I came across this source code info on their GitHub page: https://github.com/dborth/vbagx/blob...utils/wiidrc.h

Looking at this code:

#define WIIDRC_BUTTON_A 0x8000
#define WIIDRC_BUTTON_B 0x4000
#define WIIDRC_BUTTON_X 0x2000
#define WIIDRC_BUTTON_Y 0x1000
#define WIIDRC_BUTTON_LEFT 0x0800
#define WIIDRC_BUTTON_RIGHT 0x0400
#define WIIDRC_BUTTON_UP 0x0200
#define WIIDRC_BUTTON_DOWN 0x0100
#define WIIDRC_BUTTON_ZL 0x0080
#define WIIDRC_BUTTON_ZR 0x0040
#define WIIDRC_BUTTON_L 0x0020
#define WIIDRC_BUTTON_R 0x0010
#define WIIDRC_BUTTON_PLUS 0x0008
#define WIIDRC_BUTTON_MINUS 0x0004
#define WIIDRC_BUTTON_HOME 0x0002
#define WIIDRC_BUTTON_SYNC 0x0001

The string highlighted in RED above is what I assume are the HEX values for the ZL and ZR buttons on the GamePad, going back to the settings.xml file, I worked out that:

button number=8 is the L button, since the value was "0", since mapping to ZL game us a bank value.
button number=9 is the R button and I have remapped it to ZR which gave me the value of "64", below is the string I'm talking about.

<button number="9" assignment="64" />

Now if you do a HEX to BINARY conversion:

HEX: 0x0040 => BINARY: 64

Bingo, I have found the value of the ZR button!, now lets convert the ZL HEX.

HEX: 0x0080 => BINARY: 128

Another Bingo, I have found the ZL value, replaced the assignment="0" value to "128", now gives us the ZL button mapping!

Not sure where the issue lies but the same ZL issue also happens in their other emulators, FCE Ultra GX and Snes9x GX. It's either their coding, they must have missed something, or it's something to do with the inject itself????

Since you were able to contact the devs, are you above to provide the above info to them to have a look, I'm no dev, so maybe they can make sense of what the issue is."

**Comment by dborth** [comment]
Okay, I've found the issue. I'll work on a fix.
