### ISSUE TITLE
autocrash when load from smb

### ISSUE THREAD

**Issue by TiroDvD** [dborth/vbagx#374]
vbagx v2.3.9

1. restore default configuration.
2. configure SMB
3. set Load Device to "Network".
4. Exit.
5. Load vbagx.
6. autocrash. Dump info: https://imgur.com/a/Zy3oCSE

Notes: 

- Win7 Prof.
- Rom folder Shared by Everyone Read/Write/Control.
- Saves folder Shared by Everyone Read/Write/Control.
- Able to actual load, run, save, savestate, load savestate files from Network correctly and multiple times. Autocrashes when exit and run vbagx.
- Autocrashes whether or not files loaded or not.
- Does not autocrash when Load Device is set to "SD".
- If autocrashes, fixed by manual editing "settings.xml" back to Load Device to "0".
- autocrash did not occur in "Visual Boy Advance M GX 2.3.2"
![vgagx_error_dump_network](https://user-images.githubusercontent.com/38301583/56046827-bee0c080-5d09-11e9-8645-72adc2de41f7.png)

**Comment by dborth** [comment]
This is actually already fixed, I just haven't gotten around to releasing a new version. Maybe I'll do that.
