### ISSUE TITLE
Add different low resolution widths

### ISSUE THREAD

**Issue by filevans** [dborth/vbagx#376]
Hello, instead of just having '240p' could you allow some extra widths like retroarch
as I like to have the GBA fill up the screen width on 240p so instead of using a common 320 or 640 which gives big left and right borders, please could you add something like 512 (x240) as a selectable width or 256 (x240) so the GBA screen fills up the width, more, 240x2 = 480 width would fit on 512 width or 240x1 would fit on 256 (allowing for some of the screen outside the tv overscan).

**Comment by dborth** [comment]
Sounds like a good idea, but I'm not doing it. If someone submits a pull request I'll merge it.

**Comment by filevans** [comment]
![IMG_20190626_111914](https://user-images.githubusercontent.com/14978933/60204990-0aeecc00-9848-11e9-8fb9-2c27f148be05.jpg)

That's what it looks like on retroarch. Looks really good
