### ISSUE TITLE
Button mapping always default with Wii U Pro Controller

### ISSUE THREAD

**Issue by lotsa-spaghetti-ouo** [dborth/vbagx#378]
I found a minor bug in 2.4.0 where the emulator only uses default mappings for the Wii U Pro Controller, regardless of what's set in the config menu. The menu appears to function correctly by showing and saving the config file mapping as expected, but the mapping that's actually used in-game is the default (all matching GBA buttons except with Y set to B and B set to A). This happens on the original Wii and it only appears to happen with the Pro Controller specifically (the only controller I wasn't able to test was the Classic Controller, but custom mappings on other controllers work fine).

**Comment by dborth** [comment]
this is fixed!
