### ISSUE TITLE
Exception (DSI) Crash Ocurred when loading Super Puzzle Fighter II.

### ISSUE THREAD

**Issue by el-quinto** [dborth/vbagx#397]
All other roms I've tried have worked fine, but cannot get Super Puzzle Fighter II to work at all. It crashes as soon as I try to load the game. I get a black screen which says "Exception (DSI) Crash Ocurred " and a lot of numbers.

**To Reproduce**
Start vbagx. Load Super Puzzle Fighter II. Crash

I'm using latest versions of Homebrew Launcher, USB Loader GX and Visual Boy Advance GX.

**Comment by dborth** [comment]
Might be a problem with VBA-M on which this is based. Not sure. Sorry, don't plan to look at this.
