### ISSUE TITLE
VBAGX SAVE DATA ISNT WORKING

### ISSUE THREAD

**Issue by glitcherboyadvance246** [dborth/vbagx#399]
So i was playing some games on the emulator. Saved and exited the emulator. Next time i used it, i noticed all my hard earned saves are gone on every game. (I have save states but still) Can you guys fix this ?
Edit: i just realized it also happens to snes9gx :(

**Comment by Arlisbloxer05** [comment]
Is your SD Card locked

**Comment by glitcherboyadvance246** [comment]
> Is your SD Card locked

No its not locked. Im using a sandisk micro sd card with a SanDisk micro sd card adapter. It had been working just fine untill the time around i posted. I don't get what's wrong. :(

**Comment by dborth** [comment]
Sorry don't have an answer for you. They work fine for me.
