### ISSUE TITLE
Load State Error v2.4.0 (Both vbga and snes9xgx)

### ISSUE THREAD

**Issue by JBradBarnes** [dborth/vbagx#401]
Thanks for all you have accomplished on this app!

**Describe the bug**
Platform: Wii, Ver. 4.3U, sd card load, Boot Mii
File structure: Exactly the same as zip extract
sd:
-apps (in root)
--vbagx
-vbagx
--roms 
---gba (also have gbc)
----a-c (roms are nested vbagx/roms/gba/a-c )
--saves (in vbagx)

** Bug **
1. When loading a SRAM save state, the game resets as opposed to loading the state.
2. The trying to load the ROM changes the configure setting for the load in the config menu .

**To Reproduce**
- Both from loading from channel and directly from the Homebrew channel
1. settings> saving and loading> Set the load folder to vbagx/saves
2. play a ROM (any ROM) home > save > New SRAM
3. home > load > SRAM from above
- The game then resets
- settings> saving and loading> the load folder has ben reset to vbagx/roms/gba/a-c

The same bug is also plaguing my snes9xgx, may that will help narrow it to another package?

I really love the UI in this app!

**Comment by dborth** [comment]
Sorry you're having trouble but this is working fine for me.
- the load folder changes automatically to remember the last path you were browsing. that's normal
- loading sram is expected to reset the game. loading state should bring you directly to where you left off
- ask on a forum like gbatemp if you need more help

**Comment by JBradBarnes** [comment]
Thanks, I see. I did not understand SRAM correctly and was trying to use it as a snapshot.
For anyone else who hits this: https://gbatemp.net/threads/snes9x-gx-save-system-question.164226/
