### ISSUE TITLE
Boot.dol incompatible with WiiVC Injector

### ISSUE THREAD

**Issue by timbobaggins** [dborth/vbagx#405]
I don't know if this is a problem with vba gx or with Teconmoon's injector but since VBA GX version 2.3.7 Teconmoon's injector will throw an exception and prevent the forwarder channel from being built, without this, there's no actual way to use the wii u gamepad.

**Comment by dborth** [comment]
I don't try to inject the entire dol, instead I inject a custom version of https://github.com/FIX94/nintendont-autoboot-forwarder

Works fine and makes it easy to upgrade needing to rebuild the wiivc channel
