### ISSUE TITLE
compile vbagx on windows

### ISSUE THREAD

**Issue by greg-deng** [dborth/vbagx#406]
**Feature requests will be closed immediately!**

**Describe the bug**
After compiling on windows, an error occurs when running on Wii

**To Reproduce**

**Expected behavior**

**Screenshots**
![d](https://user-images.githubusercontent.com/68487538/87865823-3fca4580-c9ac-11ea-9a2d-15d2ef6e87f5.png)
![IMG_2547 HEIC JPG](https://user-images.githubusercontent.com/68487538/87865825-4953ad80-c9ac-11ea-9f42-cbad9ea847a9.JPG)

**Comment by dborth** [comment]
I would expect this is because you used the freetype built in the devkitppc portlibs. You need an older copy, the one included in this repo works.

**Comment by greg-deng** [comment]
thanks
