### ISSUE TITLE
Garbled Pixels/Graphics

### ISSUE THREAD

**Issue by Immortallix** [dborth/vbagx#408]
**Describe the bug**
In VBAgx, snes9xgx, & fceugx on Wii I am getting garbled/distorted pixels in most games. I got these on the previous version, I deleted all the old files & folders and replaced them with clean copies of the newest versions of each and still got the same issues. Graphical glitches are apparent as soon as a ROM loads. Was wondering if it could be my SD card, so I tried reformatting it, still no luck. Also tried out Genesis Plus GX, no issues there. 

**Screenshots**
I've posted screenshots from each emulator.
Issue is worse in snes & gba. 

![Metroid Fusion](https://user-images.githubusercontent.com/48418609/88124619-8c27a800-cb9b-11ea-926e-761497f55fa8.png)
![Super Mario All-Stars (U)  !](https://user-images.githubusercontent.com/48418609/88124621-8c27a800-cb9b-11ea-84e4-0ba9d5b77989.png)
![Super Mario Bros](https://user-images.githubusercontent.com/48418609/88124623-8cc03e80-cb9b-11ea-9583-e335968e1af2.png)

Mirror for images:
https://imgur.com/a/VU2nq9V

**Comment by dborth** [comment]
I'm at a loss to explain this. I've never seen anything like this before and can't reproduce this.

**Comment by Immortallix** [comment]
Didn't exactly figure out what caused it in the first place, but I deleted all my Nes, Snes, & GBA roms & replaced them with new downloads (just replaced them with a backup when I tried formatting before), and haven't gotten the problem since. Strange since its the same files & SD card I've had for years.
