### ISSUE TITLE
Classic nes series not response in pad

### ISSUE THREAD

**Issue by Ahmedcity** [dborth/vbagx#411]
**Describe the bug**

I tested 2 games classic nes series
1) Zelda nes - 2) zelda adventure of link (USA,EUROPE) :
If i press start for launching game nothing work
Any touch response

**To Reproduce**

Just launch the game

Thanks for your work bro 🥇

**Comment by dborth** [comment]
You're right! I just tried it myself, NES emulation through VBA (which is itself an emulator!) appears to have an issue. The controller responses are very laggy/intermittent - if I mash the buttons enough it'll do something but it's completely unusable. I don't plan to look into this. Closing.

**Comment by Ahmedcity** [comment]
Thanks for response
Yes emulate correctly the nes classic series or any other collection emulation is not a priority at moment, maybe in aother day, have a good day 
👌😭
