### ISSUE TITLE
SD2SP2 game slowness/jitters

### ISSUE THREAD

**Issue by Qua2k** [dborth/vbagx#412]
Details:
I am using a GameCube with GC Loader and SD2SP2 using the latest Swiss. Emulator loads fine, loads each rom ok with no issues, but it is only when the rom runs that each rom is slow and jittery. I have tested the emulator as well on the GC Loader sd card and same results--finds and loads the roms with no issues, just slow and jittery when it starts and runs.

**Comment by Qua2k** [comment]
if I force the video aspect to 480i, it seems to run a lot better but still a little slow. i have mixed and matched  in-game video settings within the emulator and have found leaving everything default but forcing the video to 480i, seems to get the best... not perfect.. results.

**Comment by Alex13mod** [comment]
It may be an emulation issue since I'm Using VBA GC 2.4.2 with SD2SP2 and All GBA games are studdering.

**Comment by dborth** [comment]
yeah it is what it is...
