### ISSUE TITLE
artwork not loading

### ISSUE THREAD

**Issue by supersonicjc** [dborth/vbagx#417]
**Feature requests will be closed immediately!**

**Describe the bug**
when loading the rom up there should be a display of the screenshot taken with the emu and now even with the path correct in settings there is no artwork

i tried to reset the settings file and to relabel it as another file entirely and the artwork wont show up, not a major bug by any means but its there, 
sorry for bothering you with this too in advance

**Comment by Papy-G** [comment]
There seem to have quite the same issue on another of the emulators with covers png bigger than 512x512, are your artworks high res?

**Comment by supersonicjc** [comment]
no.. the artwork im talking about is when you make the screenshot using the camera feature of the emu to take pics for artwork, so what ever the native shot size is, its taking the pic but not saving it anywhere and i had my other artwork box and otherwise at sizes 320x240 or 300x300 depending on the box region to make sure it looked nice, those load just not the screen shots

**Comment by dborth** [comment]
looks like it's related - the artwork is now limited to 512x512 to prevent people from loading images that are too large and crashing the emulator. But that's not going to work for screenshots, which can be up to 640x480. So I've changed the limitations to 640x480 to accommodate this.
