### ISSUE TITLE
VBAGX Channel Installer Crash to Exception (DSI) Occurred

### ISSUE THREAD

**Issue by bigbsonnier** [dborth/vbagx#419]
**Feature requests will be closed immediately!**

**Describe the bug**
When i try to install VBAGX channel installer it crashes out to exception (dsi) occurred
I tried just running the VBAGX program and it ran fine, i should have tried a few more time just to make sure it wasn't a fluke sorry. 
Sometimes it crashes out to the exception before i have a chance to select the installer.

**To Reproduce**
1. go to homebrew channel
2. select VBAGX channel installer
3. select install

**Expected behavior**
channel installer working as intended

**Screenshots**
below is a screenshot of the dump.
I'm running Homebrew channel ios58
![VBAGX Channel Installer Crash Dump](https://user-images.githubusercontent.com/72210744/108898577-f8a8d080-75dc-11eb-9bdf-4c0af0e52149.jpg)

**Comment by dborth** [comment]
That's unfortunate. Not sure how to help with this.
