### ISSUE TITLE
SD card not Found in SP2

### ISSUE THREAD

**Issue by DbXxX** [dborth/vbagx#423]
**Describe the bug**
In version 2.4.5 for GameCube, when I select the SD in SP2 option, it shows that the SD card is not found, being that from there I am executing vbagx.dol

**To Reproduce**
1. Run Swiss from DVD
2. On Swiss run vbagx.dol from SD in SP2
3. On VBAGX select SD in SP2

**Expected behavior**
See the list of ROMs found in the SD

**Comment by LiquidSebbey** [comment]
I am also having this issue, exactly! What can I do about it?
1. Run Swiss though MC with Shinehax
2. Select vbagx and load it from the SP2-SD card
3. Its trying to read DVD and gives up (make sense)
4. Select SD in SP2
5. "Error" SD card not found! [Retry] [Cancel]
