### ISSUE TITLE
microSD sd2sp2 formatted as exFAT not detected

### ISSUE THREAD

**Issue by lacksfish** [dborth/vbagx#424]
**Describe the bug**
Not loading microSD card in sd2sp2.

**To Reproduce**
Format microSD card to exFAT - I used a Kingston SDCS2 64 GB

**Expected behavior**
List SD content

I will try to use the same microSD card formatted as fat32, but could this be an issue with using the exFAT filesystem? It was supported by Swiss, that's why I just went with it.

If exFAT support is missing in vbagx, perhaps it could be a nice small addition? Been briefly browsing the codebase but couldn't find where the magic happens.

**Comment by lacksfish** [comment]
Ok so I've just stumbled on this: https://github.com/dborth/vbagx/issues/421

Perhaps it would be possible to add exFAT support? Could you give me a hint towards where to look in the code? Would love to help if possible!

**Comment by dborth** [comment]
exfat isn't supported. You'd have to look into whatever Swiss is doing and port that to this.

**Comment by lacksfish** [comment]
https://github.com/dborth/vbagx/blob/master/source/fileop.cpp#L222

Would you know, is libfat also used in snes98xgx?
