### ISSUE TITLE
GBA games in VBA GX 2.4.5 run very slow :(

### ISSUE THREAD

**Issue by saulfabregwiivc** [dborth/vbagx#425]
**Feature requests will be closed immediately!**

**Describe the bug**
All GBA (Game Boy Advance) games run very slow in the latest version of VBA-GX v2.4.5, specially Kirby: Nightmare in Dream Land. But GB and GBC games run normally without any slowdowns.
Can you fix it please?

**To Reproduce**
I just loaded the ROM from the menu and it loads and runs, but the speed is slow.

**Expected behavior**
I was expecting the GBA games run flawlessly (in normal speed) and NOT with slowdowns.

**Screenshots**

**Comment by dborth** [comment]
Sorry, there's no "fix it" button on my side - I can't magically make it faster. Not saying no-one can - just saying I don't intend to put that kind of time in. It is what it is.
