### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by cstout1** [dborth/vbagx#443]
### Describe your question

Is there any way to change the assigned turbo mode button? On the classic controller it’s set to the right stick which is awkward when using the dpad and regular buttons. Would love to switch it to R or ZR but don’t see an option anywhere obvious.

**Comment by dborth** [comment]
No there isn't.

**Comment by saulfabregwiivc** [comment]
I could try implementing the Turbo Mode remap from Snes9x GX, but unfortunately this will take me some time.

**Comment by saulfabregwiivc** [comment]
I could try implementing the Turbo Mode remap from Snes9x GX, but unfortunately this will take me some time.
