### ISSUE TITLE
[Issue]: Kirby Tilt 'n' Tumble (GBC) does not save any savedata

### ISSUE THREAD

**Issue by saulfabregwiivc** [dborth/vbagx#451]
### Describe the bug

On VBAGX, the game Kirby Tilt 'n' Tumble doesn't save any save data.
It says "Saving..." when saves data but when i reset or next time i load the game, the File Select screen just shows there's nothing saved (all savefiles says EMPTY / NO DATA).

But oddly on VBA-M 2.1.4 the game saves the savedata fine, and the savedata shows on "File Select".

### To Reproduce

1. Load the game ROM (unpatched, the original one.)
2. Enable "Match Wii Controls".
3. Play for a while until you see a "Saving..." screen, then let it save.
4. Reset the game, and choose "GAME START". The file select shows there's no saved data.

### Expected behavior

I expected VBA-GX to save the game data of Kirby Tilt 'n' Tumble (the saved data appears on "File Select" screen.

**Comment by saulfabregwiivc** [comment]
@bladeoner 

Pinging you cause i think you know more of the code handling in VBA-GX.

Recently, a collaborator of VBA-M made this fix for fix saving in Kirby Tilt 'n' Tumble, but since this was made in updated upstream VBA-M and this emu is based on an old version of VBA-M, can you help me backporting this fix to VBA-GX?

https://github.com/visualboyadvance-m/visualboyadvance-m/commit/803ab35269a9c5c66f3c910be7f6f3cdb6d5290d

Specifically in this part https://github.com/visualboyadvance-m/visualboyadvance-m/commit/803ab35269a9c5c66f3c910be7f6f3cdb6d5290d#diff-5a2c28b55ff0b6d6d727a379761f0ec9600d3f03151f02239264374c5298c21fR426

Thanks

**Comment by saulfabregwiivc** [comment]
Nevermind, i managed to fix this issue at https://github.com/dborth/vbagx/pull/459.

**Comment by dborth** [comment]
Thanks for digging in and finding a fix!
