### ISSUE TITLE
[Issue]: Stuck on "Loading DVD..." screen after launching

### ISSUE THREAD

**Issue by Soundtoxin** [dborth/vbagx#453]
### Describe the bug

I am using a GameCube and when launching vbagx I get stuck on a loading screen and can't do anything.

### To Reproduce

- put relevant files on an SD card, insert into SD2SP2 adapter
- boot into Swiss
- launch vbagx

### Expected behavior

I don't know why it's doing anything with the DVD drive. I would either expect to not see this screen at all (especially with my drive empty) or to have an option to cancel out of it.

**Comment by Soundtoxin** [comment]
I also have this issue with snes9xgx, and this seems similar to the following issue:
https://github.com/dborth/snes9xgx/issues/927

**Comment by Soundtoxin** [comment]
https://www.reddit.com/r/Gamecube/comments/hef1t9/comment/g26zvn6/?context=3

I found this post. My SD card is also exfat I believe. Is exfat not supported?

I guess https://github.com/dborth/vbagx/issues/424 and https://github.com/dborth/vbagx/issues/421 are also relevant then.

**Comment by The-Randalorian** [comment]
I had the same issue on an exfat card which I reformatted to fat32. That also worked for me, so I guess exfat just isn't supported.

I think any GC game easily fits into the 4GB file limit of exfat, so formatting to fat32 is probably just a good idea anyway.
