### ISSUE TITLE
[Issue]: Crash while loading vWii VBA GX

### ISSUE THREAD

**Issue by grayhax** [dborth/vbagx#461]
### Describe the bug

When I start VBA GX, it sits at the loading screen for a couple of seconds and then it crashes.

### To Reproduce

Starting the Channel

### Expected behavior

For it to load

**Comment by dborth** [comment]
It's not crashing, it's exiting. All the channel does is try to load the emulator. Put it on the SD card as per the readme.

**Comment by grayhax** [comment]
I see.
