### ISSUE TITLE
[Issue]: Channel installer broken?

### ISSUE THREAD

**Issue by mawatts25** [dborth/vbagx#476]
### Describe the bug

Latest versions of HB and everything. Channel installer on Wii (once installed) just opens to the main screen, you click start, and it goes black then back to the wii main menu

### To Reproduce

Channel installer on Wii just opens to the main screen, you click start, and it goes black then back to the wii main menu

### Expected behavior

Opens VBAGX

**Comment by dborth** [comment]
Not broken, all it does is load the emu, which has to be on your sd or usb
