### ISSUE TITLE
[Issue]: GB Video Settings not saved 

### ISSUE THREAD

**Issue by captainbk** [dborth/vbagx#477]
### Describe the bug

Settings for specific stretch parameters for GB/GBC aren't saved, or are immediately reset.

I've tried setting them in app as well as editing the settings on the PC.

### To Reproduce

Set gb zoom parameters (154v, 160h) in program.
Restart program, or select new game. Parameters reset.

Edit settings file in notepad. Change parameters. Put sd in Wii U, open settings in program, it has changed back to 100. Open settings file in notepad, can see that zoom parameters set back to 1.00

Open settings in notepad, change parameters to 1.54 and 1.60, Make file read only. Load in Wii u, zoom settings show in program as both being 100%. Exit program, move sd back to PC. File is still read only, and zoom parameters are still shown as 1.54 and 1.60.

Filtering, scaling, and y shift settings are saved as intended.

### Expected behavior

Hoping the video would always load with the same dimensions.

**Comment by dborth** [comment]
Not a bug, that's because the settings have a range set of 0.5 - 1.5. Are you suggesting a different max, and if so what should it be?

	if(!(GCSettings.gbZoomHor > 0.5 && GCSettings.gbZoomHor < 1.5))
		GCSettings.gbZoomHor = 1.0;
	if(!(GCSettings.gbZoomVert > 0.5 && GCSettings.gbZoomVert < 1.5))
		GCSettings.gbZoomVert = 1.0;

**Comment by captainbk** [comment]
For GB/GB  - On a US Wii U, with stretch to fit selected, 1.54 vertical and
1.6 horizontal will fill the full screen.
On a regular US Wii, 1.5 vertical and 1.6 horizontal will fill the full
screen.
