### ISSUE TITLE
[Issue]: VBA keeps skipping frames

### ISSUE THREAD

**Issue by moomeow96** [dborth/vbagx#479]
### Describe the bug

Every so often, VBA GX will decide to skip a couple of frames, which, most of the time, distracts me. And the worst part is, it's random.

### To Reproduce

Just load up a game (I used Mario and Luigi: Superstar Saga), and let it run.

### Expected behavior

I expected it to let me play the game without any interruptions.

### Relevant log output

```shell
N/A
```

### Screenshots

N/A

**Comment by dborth** [comment]
Sorry, unfortunately this is because the Wii hardware is pretty limited so the emulation speed isn't always perfect. Not much I can do.

**Comment by moomeow96** [comment]
That's okay. Sorry that I wasn't able to give you more information than I did.
